// vue-demo/src/views/PasswordManager.vue
<template>
  <v-layout justify-center mt-5 mx-4>
    <v-flex xs12 sm11 md10 lg8 xl6>
      <v-layout row wrap>
        <v-flex xs12>
          <v-layout row align-center justify-start mb-3>
            <v-flex shrink mr-3>
              <v-icon large>shield</v-icon>
            </v-flex>
            <v-flex>
              <div class="title">Passwords</div>
              <div class="subheading">View and Manage all your passwords</div>
            </v-flex>
          </v-layout>
        </v-flex>
        <v-flex xs12>
          <v-layout align-center>
            <v-flex>
              <v-select
                v-model="selectedCategory"
                :items="categories"
                label="Category"
                item-text="name"
                return-object
                hint="View passwords in specific categories."
                persistent-hint
                style="width: 220px"
              ></v-select>
            </v-flex>
            <v-flex shrink>
              <v-btn color="primary" @click="addNewPassword">
                <v-icon left>add_circle</v-icon>Add
              </v-btn>
            </v-flex>
          </v-layout>
        </v-flex>
        <v-flex xs12 mt-3>
          <v-divider></v-divider>
        </v-flex>
        <v-flex xs12 mt-3>
          <div v-if="isLoadingPasswords" class="text-xs-center">
            <v-progress-circular
              :size="50"
              color="primary"
              indeterminate
            ></v-progress-circular>
          </div>
          <div
            v-else-if="filteredPasswords.length === 0"
            class="title text-xs-center"
          >
            {{
              selectedCategory.id === 0
                ? 'You have no passwords yet. Get going and add some.'
                : 'No passwords in this category.'
            }}
          </div>
          <v-list v-else two-line>
            <v-list-tile
              v-for="password in filteredPasswords"
              :key="password.id"
            >
              <v-list-tile-content>
                <v-list-tile-title>{{ password.appName }}</v-list-tile-title>
                <v-list-tile-sub-title>{{
                  password.appUrl
                }}</v-list-tile-sub-title>
              </v-list-tile-content>

              <v-list-tile-action>
                <v-btn
                  icon
                  ripple
                  @click="copyPasswordToClipboard(password.id)"
                >
                  <v-icon color="grey">filter_none</v-icon>
                </v-btn>
              </v-list-tile-action>
              <v-list-tile-action>
                <v-btn icon ripple>
                  <v-icon
                    color="grey"
                    @click="editExistingPassword(password.id)"
                    >edit</v-icon
                  >
                </v-btn>
              </v-list-tile-action>
              <v-list-tile-action>
                <v-btn icon ripple>
                  <v-icon
                    color="grey"
                    @click="deleteExistingPassword(password.id)"
                    >delete</v-icon
                  >
                </v-btn>
              </v-list-tile-action>
            </v-list-tile>
          </v-list>
        </v-flex>
      </v-layout>
    </v-flex>
  </v-layout>
</template>
<script>
import { AzkabanService } from '../services/AzkabanService';

export default {
  methods: {
    addNewPassword() {
      this.$router.push('/password');
    },

    editExistingPassword(id) {
      this.$router.push(`/password/${id}`);
    },

    deleteExistingPassword(id) {
      AzkabanService.deletePassword(id);
      let passwordToDelete = this.passwords.find(password => password.id);
      let index = this.passwords.indexOf(passwordToDelete);
      this.passwords.splice(index, 1);
    },

    copyPasswordToClipboard(id) {
      let passwordToCopy = AzkabanService.getPassword(id);
      AzkabanService.copyToClipboard(passwordToCopy.password);
    }
  },
  computed: {
    filteredPasswords() {
      if (!this.passwords) {
        return [];
      }

      if (this.selectedCategory.id !== 0) {
        return this.passwords.filter(
          password => password.category === this.selectedCategory.id
        );
      } else {
        return this.passwords;
      }
    }
  },
  mounted() {
    this.isLoadingPasswords = true;
    AzkabanService.getPasswords()
      .then(passwords => {
        this.passwords = passwords;
        this.isLoadingPasswords = false;
      })
      .catch(() => {
        this.isLoadingPasswords = false;
      });
  },
  data() {
    return {
      categories: AzkabanService.categories,
      selectedCategory: AzkabanService.categories[0],
      passwords: [],
      isLoadingPasswords: false
    };
  }
};
</script>

// angular-demo/src/app/components/password-manager.component.ts
import { Component } from '@angular/core';
import { AzkabanService } from '../../services/AzkabanService';
import { Router } from '@angular/router';

@Component({
  templateUrl: './password-manager.component.html',
  styleUrls: ['./password-manager.component.css']
})
export class PasswordManager {
  categories = AzkabanService.categories;

  selectedCategory = AzkabanService.categories[0];

  passwords = [];
  isLoadingPasswords = false;

  constructor(private router: Router) {}

  ngOnInit() {
    this.isLoadingPasswords = true;
    AzkabanService.getPasswords()
      .then(passwords => {
        this.passwords = <any[]>passwords;
        this.isLoadingPasswords = false;
      })
      .catch(error => (this.isLoadingPasswords = false));
  }

  addNewPassword() {
    this.router.navigate(['/password']);
  }

  editExistingPassword(id) {
    this.router.navigate([`/password`, id]);
  }

  copyPasswordToClipboard(id) {
    let passwordToCopy = AzkabanService.getPassword(id);
    AzkabanService.copyToClipboard(passwordToCopy.password);
  }

  deleteExistingPassword(id) {
    AzkabanService.deletePassword(id);
    let passwordToDelete = this.passwords.find(password => password.id);
    let index = this.passwords.indexOf(passwordToDelete);
    this.passwords.splice(index, 1);
  }

  get filteredPasswords() {
    if (!this.passwords) {
      return [];
    }

    if (this.selectedCategory.id !== 0) {
      return this.passwords.filter(
        password => password.category === this.selectedCategory.id
      );
    } else {
      return this.passwords;
    }
  }
}

<div fxLayout="row wrap" fxLayoutAlign="center center">
  <div
    fxFlex.lt-xl="50%"
    fxFlex.lt-lg="66%"
    fxFlex.lt-md="83%"
    fxFlex.lt-sm="91%"
    fxFlex.lt-xs="100%"
    fxLayout="row wrap"
    fxLayoutAlign="center center"
  >
    <div fxFlex="100%" style="margin-top: 50px;">
      <div fxLayout="row wrap" fxLayoutAlign="space-between center">
        <div fxFlex="100%" fxLayout="row wrap" fxLayoutAlign="start center">
          <div fxFlex="55px">
            <mat-icon style="font-size: 32px">shield</mat-icon>
          </div>
          <div fxFlex="">
            <h2 class="mat-title" style="margin-bottom: 0">
              Passwords
            </h2>
            <h3 class="mat-subheading" style="margin-top: 0">
              View and Manage all your passwords
            </h3>
          </div>
        </div>

        <div fxFlex="">
          <mat-form-field style="min-width: 220px">
            <mat-select placeholder="Category" [(value)]="selectedCategory">
              <mat-option
                *ngFor="let category of categories"
                [value]="category"
              >
                {{ category.name }}
              </mat-option>
            </mat-select>
            <mat-hint>View passwords in specific categories.</mat-hint>
          </mat-form-field>
        </div>
        <div>
          <button (click)="addNewPassword()" mat-raised-button color="primary">
            <mat-icon style="margin-right: 10px">add_circle</mat-icon>
            Add
          </button>
        </div>
      </div>
    </div>
    <div fxFlex="100%" style="margin-top: 15px">
      <mat-divider></mat-divider>
    </div>
    <div fxFlex="100%" style="margin-top: 10px" fxLayoutAlign="center center">
      <ng-container *ngIf="isLoadingPasswords">
        <mat-spinner></mat-spinner>
      </ng-container>
      <ng-container *ngIf="!isLoadingPasswords && filteredPasswords.length > 0">
        <mat-list style="width: 100%">
          <mat-list-item *ngFor="let password of filteredPasswords">
            <h4 matLine>{{ password.appName }}</h4>
            <p matLine>{{ password.appUrl }}</p>
            <mat-action-list>
              <div fxLayout="row">
                <div fxFlex="">
                  <button
                    mat-icon-button
                    (click)="copyPasswordToClipboard(password.id)"
                  >
                    <mat-icon>filter_none</mat-icon>
                  </button>
                </div>
                <div fxLayout="row">
                  <button
                    mat-icon-button
                    (click)="editExistingPassword(password.id)"
                  >
                    <mat-icon>edit</mat-icon>
                  </button>
                </div>
                <div fxLayout="row">
                  <button
                    mat-icon-button
                    (click)="deleteExistingPassword(password.id)"
                  >
                    <mat-icon>delete</mat-icon>
                  </button>
                </div>
              </div>
            </mat-action-list>
          </mat-list-item>
        </mat-list>
      </ng-container>
      <ng-container
        *ngIf="!isLoadingPasswords && filteredPasswords.length === 0"
      >
        <div class="mat-title" style="text-align:center">
          {{
            selectedCategory.id === 0
              ? 'You have no passwords yet. Get going and add some.'
              : 'No passwords in this category.'
          }}
        </div>
      </ng-container>
    </div>
  </div>
</div>
