// vue-demo/src/views/PasswordManager.vue
<template>
  <v-layout justify-center mt-5 mx-4>
    <v-flex xs12 sm11 md10 lg8 xl6>
      <v-layout row wrap>
        <v-flex xs12>
          <v-layout row align-center justify-start mb-3>
            <v-flex shrink mr-3>
              <v-icon large>shield</v-icon>
            </v-flex>
            <v-flex>
              <div class="title">Passwords</div>
              <div class="subheading">View and Manage all your passwords</div>
            </v-flex>
          </v-layout>
        </v-flex>
        <v-flex xs12>
          <v-layout align-center>
            <v-flex>
              <v-select
                v-model="selectedCategory"
                :items="categories"
                label="Category"
                item-text="name"
                return-object
                hint="View passwords in specific categories."
                persistent-hint
                style="width: 220px"
              ></v-select>
            </v-flex>
            <v-flex shrink>
              <v-btn color="primary" @click="addNewPassword">
                <v-icon left>add_circle</v-icon>Add
              </v-btn>
            </v-flex>
          </v-layout>
        </v-flex>
        <v-flex xs12 mt-3>
          <v-divider></v-divider>
        </v-flex>
        <v-flex xs12 mt-3>
          <div v-if="isLoadingPasswords" class="text-xs-center">
            <v-progress-circular
              :size="50"
              color="primary"
              indeterminate
            ></v-progress-circular>
          </div>
          <div
            v-else-if="filteredPasswords.length === 0"
            class="title text-xs-center"
          >
            {{
              selectedCategory.id === 0
                ? 'You have no passwords yet. Get going and add some.'
                : 'No passwords in this category.'
            }}
          </div>
          <v-list v-else two-line>
            <v-list-tile
              v-for="password in filteredPasswords"
              :key="password.id"
            >
              <v-list-tile-content>
                <v-list-tile-title>{{ password.appName }}</v-list-tile-title>
                <v-list-tile-sub-title>{{
                  password.appUrl
                }}</v-list-tile-sub-title>
              </v-list-tile-content>

              <v-list-tile-action>
                <v-btn
                  icon
                  ripple
                  @click="copyPasswordToClipboard(password.id)"
                >
                  <v-icon color="grey">filter_none</v-icon>
                </v-btn>
              </v-list-tile-action>
              <v-list-tile-action>
                <v-btn icon ripple>
                  <v-icon
                    color="grey"
                    @click="editExistingPassword(password.id)"
                    >edit</v-icon
                  >
                </v-btn>
              </v-list-tile-action>
              <v-list-tile-action>
                <v-btn icon ripple>
                  <v-icon
                    color="grey"
                    @click="deleteExistingPassword(password.id)"
                    >delete</v-icon
                  >
                </v-btn>
              </v-list-tile-action>
            </v-list-tile>
          </v-list>
        </v-flex>
      </v-layout>
    </v-flex>
  </v-layout>
</template>
<script>
import { AzkabanService } from '../services/AzkabanService';

export default {
  methods: {
    addNewPassword() {
      this.$router.push('/password');
    },

    editExistingPassword(id) {
      this.$router.push(`/password/${id}`);
    },

    deleteExistingPassword(id) {
      AzkabanService.deletePassword(id);
      let passwordToDelete = this.passwords.find(password => password.id);
      let index = this.passwords.indexOf(passwordToDelete);
      this.passwords.splice(index, 1);
    },

    copyPasswordToClipboard(id) {
      let passwordToCopy = AzkabanService.getPassword(id);
      AzkabanService.copyToClipboard(passwordToCopy.password);
    }
  },
  computed: {
    filteredPasswords() {
      if (!this.passwords) {
        return [];
      }

      if (this.selectedCategory.id !== 0) {
        return this.passwords.filter(
          password => password.category === this.selectedCategory.id
        );
      } else {
        return this.passwords;
      }
    }
  },
  mounted() {
    this.isLoadingPasswords = true;
    AzkabanService.getPasswords()
      .then(passwords => {
        this.passwords = passwords;
        this.isLoadingPasswords = false;
      })
      .catch(() => {
        this.isLoadingPasswords = false;
      });
  },
  data() {
    return {
      categories: AzkabanService.categories,
      selectedCategory: AzkabanService.categories[0],
      passwords: [],
      isLoadingPasswords: false
    };
  }
};
</script>

// react-demo/src/components/PasswordManager.js
import React, { Component } from 'react';
import { withRouter } from 'react-router-dom';
import Grid from '@material-ui/core/Grid';
import Select from '@material-ui/core/Select';
import MenuItem from '@material-ui/core/MenuItem';
import InputLabel from '@material-ui/core/InputLabel';
import FormHelperText from '@material-ui/core/FormHelperText';
import FormControl from '@material-ui/core/FormControl';
import List from '@material-ui/core/List';
import ListItem from '@material-ui/core/ListItem';
import ListItemSecondaryAction from '@material-ui/core/ListItemSecondaryAction';
import ListItemText from '@material-ui/core/ListItemText';
import IconButton from '@material-ui/core/IconButton';
import Icon from '@material-ui/core/Icon';
import Button from '@material-ui/core/Button';
import Divider from '@material-ui/core/Divider';
import Typography from '@material-ui/core/Typography';
import CircularProgress from '@material-ui/core/CircularProgress';
import { AzkabanService } from '../services/AzkabanService';

class PasswordManager extends Component {
  state = {
    selectedCategory: AzkabanService.categories[0],
    isLoadingPasswords: false
  };

  handleChange = event => {
    this.setState({ [event.target.name]: event.target.value });
  };

  addNewPassword() {
    this.props.history.push('/password');
  }

  editExistingPassword(id) {
    this.props.history.push(`/password/${id}`);
  }

  copyPasswordToClipboard(id) {
    let passwordToCopy = AzkabanService.getPassword(id);
    AzkabanService.copyToClipboard(passwordToCopy.password);
  }

  deleteExistingPassword(id) {
    AzkabanService.deletePassword(id);
    let passwordToDelete = this.passwords.find(password => password.id);
    let index = this.passwords.indexOf(passwordToDelete);
    this.passwords.splice(index, 1);
    this.setState({});
  }

  get filteredPasswords() {
    if (!this.passwords) {
      return [];
    }

    if (this.state.selectedCategory.id !== 0) {
      return this.passwords.filter(
        password => password.category === this.state.selectedCategory.id
      );
    } else {
      return this.passwords;
    }
  }

  componentDidMount() {
    this.setState({ isLoadingPasswords: true });
    AzkabanService.getPasswords()
      .then(passwords => {
        this.passwords = passwords;
        this.setState({ isLoadingPasswords: false });
      })
      .catch(() => {
        this.setState({ isLoadingPasswords: false });
      });
  }

  render() {
    const { isLoadingPasswords, selectedCategory } = this.state;

    return (
      <Grid container direction="row" justify="center">
        <Grid item xs={12} sm={11} md={10} lg={8} xl={6}>
          <Grid
            container
            direction="row"
            style={{ marginTop: 50, marginLeft: 25, marginRight: 25 }}
            alignItems="center"
            justify="space-between"
            spacing={24}
          >
            <Grid item xs={12}>
              <Grid
                container
                direction="row"
                justify="flex-start"
                alignItems="center"
                spacing={16}
              >
                <Grid item>
                  <Icon fontSize="large">shield</Icon>
                </Grid>
                <Grid item>
                  <Typography component="h2" variant="title">
                    Passwords
                  </Typography>
                  <Typography component="h2" variant="subheading">
                    View and Manage all your passwords
                  </Typography>
                </Grid>
              </Grid>
            </Grid>
            <Grid item>
              <FormControl style={{ minWidth: 120 }}>
                <InputLabel htmlFor="category-simple">Category</InputLabel>
                <Select
                  value={selectedCategory}
                  onChange={this.handleChange}
                  inputProps={{
                    name: 'selectedCategory',
                    id: 'category-simple'
                  }}
                >
                  {AzkabanService.categories.map(category => (
                    <MenuItem key={category.id} value={category}>
                      {category.name}
                    </MenuItem>
                  ))}
                </Select>
                <FormHelperText>
                  View passwords in specific categories.
                </FormHelperText>
              </FormControl>
            </Grid>
            <Grid item>
              <Button
                variant="contained"
                color="primary"
                onClick={() => this.addNewPassword()}
              >
                <Icon style={{ marginRight: 10 }}>add_circle</Icon>
                Add
              </Button>
            </Grid>
            <Grid item xs={12}>
              <Divider style={{ marginTop: 15 }} />
              {isLoadingPasswords && (
                <Grid
                  container
                  justify="center"
                  style={{ textAlign: 'center', marginTop: 15 }}
                >
                  <Grid item xs={12}>
                    <CircularProgress />
                  </Grid>
                </Grid>
              )}
              {!isLoadingPasswords && this.filteredPasswords.length > 0 && (
                <List dense={false}>
                  {this.filteredPasswords.map(password => (
                    <ListItem key={password.id}>
                      <ListItemText
                        primary={password.appName}
                        secondary={password.appUrl}
                      />
                      <ListItemSecondaryAction>
                        <IconButton
                          aria-label="View"
                          onClick={() =>
                            this.copyPasswordToClipboard(password.id)
                          }
                        >
                          <Icon>filter_none</Icon>
                        </IconButton>
                        <IconButton
                          aria-label="Edit"
                          onClick={() => this.editExistingPassword(password.id)}
                        >
                          <Icon>edit</Icon>
                        </IconButton>
                        <IconButton
                          aria-label="Delete"
                          onClick={() =>
                            this.deleteExistingPassword(password.id)
                          }
                        >
                          <Icon>delete</Icon>
                        </IconButton>
                      </ListItemSecondaryAction>
                    </ListItem>
                  ))}
                </List>
              )}
              {!isLoadingPasswords && this.filteredPasswords.length === 0 && (
                <Typography
                  component="h2"
                  variant="title"
                  style={{ textAlign: 'center', marginTop: 15 }}
                >
                  {selectedCategory.id === 0
                    ? 'You have no passwords yet. Get going and add some.'
                    : 'No passwords in this category.'}
                </Typography>
              )}
            </Grid>
          </Grid>
        </Grid>
      </Grid>
    );
  }
}

export default withRouter(PasswordManager);
