// angular-demo/src/app/components/password-details.component.ts
import { Component } from '@angular/core';
import { AzkabanService } from '../../services/AzkabanService';
import { Router, ActivatedRoute, ParamMap } from '@angular/router';
import { switchMap } from 'rxjs/operators';

@Component({
  templateUrl: './password-details.component.html',
  styleUrls: ['./password-details.component.css']
})
export class PasswordDetails {
  isSaving = false;

  password = {};

  categories = AzkabanService.categories.filter(category => category.id !== 0);

  constructor(private router: Router, private route: ActivatedRoute) {}

  ngOnInit() {}

  save() {
    this.isSaving = true;
    if (this.isNew()) {
      AzkabanService.addPassword(this.password).then(() => {
        this.isSaving = false;
        this.navigateToPasswords();
      });
    } else {
      AzkabanService.updatePassword(this.getId(), this.password).then(() => {
        this.isSaving = true;
        this.navigateToPasswords();
      });
    }
  }

  cancel() {
    this.navigateToPasswords();
  }

  navigateToPasswords() {
    this.router.navigate(['/passwords']);
  }

  getId() {
    return this.route.snapshot.paramMap.get('id');
  }

  isNew() {
    return this.getId() === undefined || this.getId() === null;
  }
}

<div
  fxLayout="row wrap"
  fxLayoutAlign="center center"
  style="margin-left: 25px; margin-right: 25px"
>
  <div
    fxFlex.lt-xl="50%"
    fxFlex.lt-lg="66%"
    fxFlex.lt-md="83%"
    fxFlex.lt-sm="91%"
    fxFlex.lt-xs="100%"
    fxLayout="row wrap"
    fxLayoutAlign="center center"
    style="margin-top: 30"
  >
    <div fxFlex="100%">
      <div fxFlex="100%" fxLayout="row wrap" fxLayoutAlign="start center">
        <div fxFlex="55px">
          <mat-icon style="font-size: 32px">shield</mat-icon>
        </div>
        <div fxFlex="">
          <h2 class="mat-title" style="margin-bottom: 0">
            {{ isNew() ? 'Add new' : 'Edit' }} Password
          </h2>
          <h3 class="mat-subheading" style="margin-top: 0">
            {{
              isNew()
                ? 'Add a new password for an app or website.'
                : 'Change the details for your existing password.'
            }}
          </h3>
        </div>
      </div>
    </div>
    <div fxFlex="100%">
      <form>
        <mat-form-field>
          <input
            required
            matInput
            name="appName"
            [(ngModel)]="password.appName"
            placeholder="App/Site Name"
          />
        </mat-form-field>
        <mat-form-field>
          <input
            matInput
            name="appUrl"
            [(ngModel)]="password.appUrl"
            placeholder="App/Site Url"
          />
          <mat-hint>Leave blank if not applicable</mat-hint>
        </mat-form-field>
        <mat-form-field>
          <mat-select placeholder="Category" [(value)]="password.category">
            <mat-option
              *ngFor="let category of categories"
              [value]="category.id"
            >
              {{ category.name }}
            </mat-option>
          </mat-select>
        </mat-form-field>
        <mat-form-field>
          <input
            required
            matInput
            name="username"
            [(ngModel)]="password.username"
            placeholder="Username"
          />
        </mat-form-field>
        <mat-form-field>
          <input
            required
            matInput
            name="password"
            [(ngModel)]="password.password"
            placeholder="Password"
          />
        </mat-form-field>
      </form>
    </div>
    <div fxFlex="100%" fxLayout="row">
      <div fxFlex="" fxLayoutAlign="end center">
        <button
          (click)="cancel()"
          mat-raised-button
          color="accent"
          style="margin-right: 15px"
        >
          Cancel
        </button>
        <button (click)="save()" mat-raised-button color="primary">
          {{ isNew() ? 'Add' : 'Save' }}
        </button>
      </div>
    </div>
  </div>
</div>

// vue-demo/src/views/PasswordDetails.vue
<template>
  <v-layout justify-center mt-5 mx-4>
    <v-flex xs12 sm11 md10 lg8 xl6>
      <v-layout row wrap>
        <v-flex xs12>
          <v-layout row justify-start>
            <v-flex shrink mr-3>
              <v-icon large>shield</v-icon>
            </v-flex>
            <v-flex>
              <div class="title">{{ isNew ? 'Add new' : 'Edit' }} password</div>
              <div class="subheading">
                {{isNew
                ? 'Add a new password for an app or website.'
                : 'Change the details for your existing password.'}}
              </div>
            </v-flex>
          </v-layout>
        </v-flex>
        <v-flex xs12>
          <v-form>
            <v-text-field v-model="password.appName" label="App/Site Name" required></v-text-field>
            <v-text-field
              v-model="password.appUrl"
              label="App/Site Url"
              hint="Leave blank if not applicable"
            ></v-text-field>
            <v-select
              :items="categories"
              label="Category"
              item-text="name"
              item-value="id"
              v-model="password.category"
            ></v-select>
            <v-text-field v-model="password.username" label="Username"></v-text-field>
            <v-text-field v-model="password.password" label="Password"></v-text-field>
          </v-form>
        </v-flex>
        <v-flex xs12>
          <div class="text-xs-right">
            <v-btn @click="cancel">Cancel</v-btn>
            <v-btn
              @click="save"
              :disabled="isSaving"
              :loading="isSaving"
              color="primary"
            >{{ isNew ? 'Add' : 'Save'}}</v-btn>
          </div>
        </v-flex>
      </v-layout>
    </v-flex>
  </v-layout>
</template>
<script>
import { AzkabanService } from '../services/AzkabanService';

export default {
  methods: {
    save() {
      this.isSaving = true;
      if (this.isNew) {
        AzkabanService.addPassword(this.password).then(() => {
          this.isSaving = false;
          this.navigateToPasswords();
        });
      } else {
        AzkabanService.updatePassword(this.getId(), this.password).then(() => {
          this.isSaving = false;
          this.navigateToPasswords();
        });
      }
    },

    cancel() {
      this.navigateToPasswords();
    },

    navigateToPasswords() {
      this.$router.push('/passwords');
    },

    getId() {
      if (this.$route) {
        return this.$route.params.id;
      }
    },

    getIsNew() {
      return this.getId() === undefined;
    }
  },
  mounted() {
    if (!this.isNew) {
      this.password = AzkabanService.getPassword(this.getId());
    }
  },
  data() {
    return {
      isNew: this.getIsNew(),
      isSaving: false,
      password: { category: 1 },
      categories: AzkabanService.categories.filter(
        category => category.id !== 0
      )
    };
  }
};
</script>
